### ISSUE TITLE
Photosynthesis and Create mod breaking server

### ISSUE THREAD

**Issue by exit151** [Zuiron/Photosynthesis#259]
Created a bunch of mods and struggled with multiple errors parsing various recipes, mostly bread.  Created several servers trying mods one at a time until I narrowed it down to two:  This mod and Create.  Below are my findings, any chance for a fix on this?
Details;
Fabric: fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0
entire mods folder:
cloth-config-11.1.136-fabric
create-fabric-0.5.1-j-build.1631+mc1.20.1
fabric-api-0.92.2+1.20.1
photosynthesis-1.20.1-0.0.25

Both mods run fine on their own, no errors, no complaints about empty ingredient recipes.  Both also run fine, separately with about 48 other mods, other than each other (lol) - Now while I'd write this off as a bummer and just some kind of random incompatibility I post this because on the modrinth page create is specifically listed and 'enjoy seamless compatibility with the Create mod, allowing....' and TBH, these two mods together were very highly desired when we were cherry picking mods for a new server!

Really hoping someone can figure out why it's not playing nice with Create, final entry here will be the full log, thanks in advance for any assistance!
Here's my $.02 from what I can read..

REI is client only - but I added it, and it is version 12.1.785, clearly newer than 12.0.xx

is also wants create-fabric 1.20.1-0.0.25, which ours is create-fabric-0.5.1.j clearly A LOT newer..  but maybe it's 'too new' and has to be an older version of create, which would possibly break other mods wanting the up to date create, but also since it's newer photosynthesis should see that and know it and it doesn't seem to...

The Log file (new, freshly created world as every attempt has been to ensure nothing glitchy remaining):
`[18:10:40] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.17.2
[18:10:41] [main/WARN]: Warnings were found!
 - Mod 'Photosynthesis' (photosynthesis) 1.20.1-0.0.25 recommends any version of create-fabric, which is missing!
	 - You should install any version of create-fabric for the optimal experience.
 - Mod 'Photosynthesis' (photosynthesis) 1.20.1-0.0.25 recommends version 12.0.634 or later of rei, which is missing!
	 - You should install version 12.0.634 or later of rei for the optimal experience.
[18:10:41] [main/INFO]: Loading 84 mods:
	- cloth-config 11.1.136
	   \-- cloth-basic-math 0.6.1
	- create 0.5.1-j-build.1631+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.11-4
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.8+1.20.1
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_base 2.3.8+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    |-- porting_lib_attributes 2.3.8+1.20.1
	   |    |-- porting_lib_common 2.3.8+1.20.1
	   |    |-- porting_lib_config 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    |-- porting_lib_fluids 2.3.8+1.20.1
	   |    |-- porting_lib_gui_utils 2.3.8+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.8+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.8+1.20.1
	   |    |-- porting_lib_utility 2.3.8+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.8+1.20.1
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_client_events 2.3.8+1.20.1
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_entity 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.8+1.20.1
	   |-- porting_lib_extensions 2.3.8+1.20.1
	   |    |-- porting_lib_attributes 2.3.8+1.20.1
	   |    |-- porting_lib_common 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    |-- porting_lib_fluids 2.3.8+1.20.1
	   |    \-- porting_lib_model_loader 2.3.8+1.20.1
	   |-- porting_lib_networking 2.3.8+1.20.1
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_obj_loader 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    \-- porting_lib_model_loader 2.3.8+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_tool_actions 2.3.8+1.20.1
	   |    \-- porting_lib_core 2.3.8+1.20.1
	   |-- porting_lib_transfer 2.3.8+1.20.1
	   |    |-- porting_lib_core 2.3.8+1.20.1
	   |    \-- porting_lib_fluids 2.3.8+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.79-MC1.20.1
	        |-- com_google_code_findbugs_jsr305 3.0.2
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.17.2
	   \-- mixinextras 0.5.0
	- java 21
	- minecraft 1.20.1
	- patchouli 1.20.1-81-FABRIC
	   \-- fiber 0.23.0-2
	- photosynthesis 1.20.1-0.0.25
[18:10:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/<username>/servers/medfabricphoto/libraries/net/fabricmc/sponge-mixin/0.16.3+mixin.0.8.7/sponge-mixin-0.16.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[18:10:41] [main/INFO]: Compatibility level set to JAVA_17
[18:10:41] [main/WARN]: Error loading class: net/minecraft/class_881 (java.lang.ClassNotFoundException: net/minecraft/class_881)
[18:10:41] [main/WARN]: @Mixin target net.minecraft.class_881 was not found porting_lib_base.mixins.json:client.BoatRendererMixin from mod porting_lib_base
[18:10:41] [main/WARN]: Error loading class: net/minecraft/class_525 (java.lang.ClassNotFoundException: net/minecraft/class_525)
[18:10:41] [main/WARN]: @Mixin target net.minecraft.class_525 was not found porting_lib_base.mixins.json:client.CreateWorldScreenMixin from mod porting_lib_base
[18:10:41] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[18:10:41] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_tool_actions.mixins.json:FishingHookRendererMixin from mod porting_lib_tool_actions
[18:10:41] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.5.0).
[18:10:42] [main/WARN]: @Final field field_11476:Lnet/minecraft/class_2758; in photosynthesis.mixins.json:ModSaplingBlock from mod photosynthesis should be final
[18:10:43] [main/WARN]: @Final field field_11009:Lnet/minecraft/class_2758; in photosynthesis.mixins.json:ModFarmlandBlock from mod photosynthesis should be final
[18:10:48] [main/INFO]: [STDOUT]: Registered Mod Sounds for photosynthesis
[18:10:48] [main/INFO]: [STDOUT]: Registered Mod Items for photosynthesis
[18:10:48] [main/INFO]: [STDOUT]: Registering ModBlocks for photosynthesis
[18:10:48] [main/INFO]: Registering particles for: photosynthesis
[18:10:48] [main/INFO]: Registering Mod Effects for photosynthesis
[18:10:48] [main/INFO]: Registering Mod Entities for photosynthesis
[18:10:48] [main/INFO]: Hello Fabric world!
[18:10:48] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:10:49] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:smoking/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:campfire_cooking/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:milling/wheat
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:splashing/wheat_flour
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:mixing/dough_by_mixing
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-j-build.1631+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/ERROR]: Parsing error loading recipe create:smelting/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[18:10:49] [main/INFO]: Loaded 36 recipes
[18:10:49] [main/INFO]: Loaded 2609 advancements
[18:10:50] [main/INFO]: Applied 1904 biome modifications to 64 of 64 new biomes in 20.42 ms
[18:10:50] [Server thread/INFO]: Starting minecraft server version 1.20.1
[18:10:50] [Server thread/INFO]: Loading properties
[18:10:50] [Server thread/INFO]: Default game type: SURVIVAL
[18:10:50] [Server thread/INFO]: Generating keypair
[18:10:51] [Server thread/INFO]: Starting Minecraft server on *:26568
[18:10:51] [Server thread/INFO]: Using epoll channel type
[18:10:51] [Server thread/INFO]: Preparing level "world"
[18:10:52] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:10:54] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[18:10:54] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[18:10:54] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[18:10:54] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[18:10:54] [Worker-Main-1/INFO]: Preparing spawn area: 1%
[18:10:55] [Server thread/INFO]: Time elapsed: 2506 ms
[18:10:55] [Server thread/INFO]: Done (4.028s)! For help, type "help"

`

**Comment by Zuiron** [comment]
its probably a newer fabric version making it incompatible (the create version u are using is using a newer fabric version). i will look into it and update the mod and build it for newer fabric version and also up the fabric-api v.

**Comment by exit151** [comment]
Awesome, appreciate it!  Yeah, I wouldn't have guessed that, but I was coming back to mention that just after posting, I also tried all other versions of create, thinking maybe one of those versions broke something (no change, however) - Thanks for everything you do!

**Comment by Zuiron** [comment]
Fixed in newest version 0.0.26

**Comment by exit151** [comment]
Sadly, for me it was not fixed..  As before, the relevant files, then the log (I did miss a couple mods in my original post that your mod recommended, they were installed, I just didn't list them)..  You'll note though, the exact same error is occuring stating that (an old) create-fabric (and rei) are both installed, and newer than listed.
mods:
cloth-config-11.1.136-fabric
create-fabric-0.5.1-d-build.1161+mc1.20.1
fabric-api-0.92.2+1.20.1
photosynthesis-1.20.1-0.0.26
Patchouli-1.20.1-81-FABRIC
modmenu-7.2.2
RoughlyEnoughItems-12.1.785-fabric
architectury-9.2.14-fabric

Log:
[12:44:48] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.17.2
[12:44:48] [main/WARN]: Warnings were found!
 - Mod 'Photosynthesis' (photosynthesis) 1.20.1-0.0.26 recommends any version of create-fabric, which is missing!
	 - You should install any version of create-fabric for the optimal experience.
 - Mod 'Photosynthesis' (photosynthesis) 1.20.1-0.0.26 recommends version 12.0.634 or later of rei, which is missing!
	 - You should install version 12.0.634 or later of rei for the optimal experience.
[12:44:48] [main/INFO]: Loading 86 mods:
	- architectury 9.2.14
	- cloth-config 11.1.136
	   \-- cloth-basic-math 0.6.1
	- create 0.5.1-d-build.1161+mc1.20.1
	   |-- com_electronwill_night-config_core 3.6.3
	   |-- com_electronwill_night-config_toml 3.6.3
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-1
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_base 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
	   |    \-- porting_lib_utility 2.1.1127+1.20
	   |-- porting_lib_brewing 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_client_events 2.1.1127+1.20
	   |    |-- mm 2.3
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_entity 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
	   |-- porting_lib_extensions 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_fake_players 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_models 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_networking 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_obj_loader 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_tags 3.0
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_tool_actions 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_transfer 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.17.2
	   \-- mixinextras 0.5.0
	- java 21
	- minecraft 1.20.1
	- patchouli 1.20.1-81-FABRIC
	   \-- fiber 0.23.0-2
	- photosynthesis 1.20.1-0.0.26
	- roughlyenoughitems 12.1.785
	   \-- error_notifier 1.0.9
[12:44:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/rooster/servers/medfabricphoto/libraries/net/fabricmc/sponge-mixin/0.16.3+mixin.0.8.7/sponge-mixin-0.16.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[12:44:48] [main/INFO]: Compatibility level set to JAVA_16
[12:44:48] [main/INFO]: Compatibility level set to JAVA_17
[12:44:48] [main/WARN]: Error loading class: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext (java.lang.ClassNotFoundException: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext)
[12:44:48] [main/WARN]: @Mixin target io.vram.frex.base.renderer.context.render.EntityBlockRenderContext was not found porting_lib_base.mixins.json:client.frex.EntityBlockRenderContextMixin from mod porting_lib_base
[12:44:49] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[12:44:49] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[12:44:49] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.5.0).
[12:44:50] [main/WARN]: @Final field field_11476:Lnet/minecraft/class_2758; in photosynthesis.mixins.json:ModSaplingBlock from mod photosynthesis should be final
[12:44:50] [main/WARN]: @Final field field_11009:Lnet/minecraft/class_2758; in photosynthesis.mixins.json:ModFarmlandBlock from mod photosynthesis should be final
[12:44:55] [main/INFO]: Definitely not up to no good
[12:44:55] [main/INFO]: [STDOUT]: Registered Mod Sounds for photosynthesis
[12:44:55] [main/INFO]: [STDOUT]: Registered Mod Items for photosynthesis
[12:44:55] [main/INFO]: [STDOUT]: Registering ModBlocks for photosynthesis
[12:44:55] [main/INFO]: Registering particles for: photosynthesis
[12:44:55] [main/INFO]: Registering Mod Effects for photosynthesis
[12:44:55] [main/INFO]: Registering Mod Entities for photosynthesis
[12:44:55] [main/INFO]: Hello Fabric world!
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[12:44:56] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[12:44:56] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[12:44:56] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[12:44:56] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[12:44:56] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[12:44:56] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[12:44:56] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items_new
[12:44:56] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:44:56] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:smoking/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:campfire_cooking/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:milling/wheat
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:splashing/wheat_flour
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:mixing/dough_by_mixing
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/ERROR]: Parsing error loading recipe create:smelting/bread
com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
	at net.minecraft.class_1869.method_8155(class_1869.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_17736(class_3957.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_3957.method_8121(class_3957.java:11) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
[12:44:57] [main/INFO]: Loaded 36 recipes
[12:44:57] [main/INFO]: Loaded 2589 advancements
[12:44:57] [main/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[12:44:57] [main/INFO]: [REI] REIPlugin starting main-reload for START.
[12:44:57] [main/INFO]: [REI] Plugins (3):
[12:44:57] [main/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:44:57] [main/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[12:44:57] [main/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[12:44:57] [main/INFO]: [REI] REIServerPlugin starting main-reload for START.
[12:44:57] [main/INFO]: [REI] Plugins (3):
[12:44:57] [main/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:44:57] [main/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[12:44:57] [main/INFO]: [REI] REIPlugin finished post-reload for START in 1.070 ms, totaling 21.35 ms.
[12:44:57] [main/INFO]: [REI] REIServerPlugin finished post-reload for START in 467.7 μs, totaling 3.330 ms.
[12:44:57] [main/INFO]: [REI] ----------------------------------------
[12:44:57] [main/INFO]: [REI] REIPlugin starting main-reload for END.
[12:44:57] [main/INFO]: [REI] Plugins (3):
[12:44:57] [main/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:44:57] [main/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI] ----------------------------------------
[12:44:57] [main/INFO]: [REI] ****************************************
[12:44:57] [main/INFO]: [REI] REIServerPlugin starting main-reload for END.
[12:44:57] [main/INFO]: [REI] Plugins (3):
[12:44:57] [main/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[12:44:57] [main/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[12:44:57] [main/INFO]: [REI] ****************************************
[12:44:57] [main/INFO]: [REI] REIPlugin finished post-reload for END in 599.5 μs, totaling 24.80 ms.
[12:44:57] [main/INFO]: [REI] REIServerPlugin finished post-reload for END in 308.8 μs, totaling 3.678 ms.
[12:44:58] [main/INFO]: Applied 1904 biome modifications to 64 of 64 new biomes in 14.99 ms
[12:44:58] [Server thread/INFO]: Starting minecraft server version 1.20.1
[12:44:58] [Server thread/INFO]: Loading properties
[12:44:58] [Server thread/INFO]: Default game type: SURVIVAL
[12:44:58] [Server thread/INFO]: Generating keypair
[12:44:58] [Server thread/INFO]: Starting Minecraft server on *:26568
[12:44:58] [Server thread/INFO]: Using epoll channel type
[12:44:58] [Server thread/INFO]: Preparing level "world"
[12:44:59] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:45:01] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[12:45:01] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[12:45:01] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[12:45:01] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[12:45:01] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[12:45:02] [Worker-Main-5/INFO]: Preparing spawn area: 99%
[12:45:02] [Server thread/INFO]: Time elapsed: 2504 ms
[12:45:02] [Server thread/INFO]: Done (3.724s)! For help, type "help"


<img width="700" height="255" alt="Image" src="https://github.com/user-attachments/assets/c51c3596-2402-4f43-a811-5239a4b6e434" /> (I did try deleting and re-adding architectury but posting so you can see the file dates to prove they were there on original post (8-18-25)

**Comment by Zuiron** [comment]
hmm. so its only on server its crashing not on client? i tried on client it works fine. but i didnt try server

**Comment by exit151** [comment]
Hey there :)  Any updates by chance on getting this working server-side?  Got some peeps that really would like to enjoy this map on our server :)
Thanks, 
Exit151
